package gov.ca.emsa.pulse.broker.domain;

public enum QueryType {
	CREATE_ACF, GET_ACF_BY_ID, GET_ALL_ACFS, EDIT_ACF, SEARCH_PATIENT,
	SEARCH_DOCUMENT, CACHE_DOCUMENT, RETRIEVE_DOCUMENT, GET_ALL_ORGANIZATIONS,
	GET_ALL_PATIENTS
}
